//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JHONNY-PC\\JHONATAN;Initial Catalog=\"SISTEMA DE VENTAS\";Persist Securi" +
            "ty Info=True;User ID=jhonny;Password=admin962011")]
        public string SISTEMA_DE_VENTASConnectionString {
            get {
                return ((string)(this["SISTEMA_DE_VENTASConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JHONNY-PC;Initial Catalog=\"SISTEMA DE VENTAS\";User ID=jhonny;Password" +
            "=admin962011")]
        public string SISTEMA_DE_VENTASConnectionString1 {
            get {
                return ((string)(this["SISTEMA_DE_VENTASConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JHONNY-PC\\SQLEXPRESS;Initial Catalog=\"SISTEMA DE VENTAS\";Integrated S" +
            "ecurity=True")]
        public string SISTEMA_DE_VENTASConnectionString2 {
            get {
                return ((string)(this["SISTEMA_DE_VENTASConnectionString2"]));
            }
        }
    }
}
